//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long Id { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string ZIP { get; set; }
        public string Place { get; set; }
        public string CountryCode { get; set; }
        public long PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
